HouseRent/Controllers/AdvertisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HouseRent.Models;
using System.IO;                    
using Microsoft.AspNetCore.Http;    
using Microsoft.AspNetCore.Hosting; 
using HouseRent.Services;
using Microsoft.Extensions.Configuration;

namespace HouseRent.Controllers
{
    public class AdvertisesController : Controller
    {
        private const string AdString = "ID,Heading,UserMail,Phone,PostTime,RentDate,Address,YoutubeLink,FlatSize,FlatType,Category,Rent,FlatDetails,UtilitiesBill,OtherBill";
        private const string CmntString = "ID,AdvertiseID,Commenter,CommentTime,Anonymous,CommentText";
        private readonly HouseRentContext _context;
        private readonly EmailService _emailService;
        private readonly IConfiguration _config;

        public AdvertisesController(HouseRentContext context, EmailService emailService, IConfiguration config)
        {
            _context = context;
            _config = config;
            _emailService = emailService;
        }

        public FileContentResult GetImg(int id)
        {
            var image = _context.Image.Find(id).FlatImage;
            return image != null ? new FileContentResult(image, "image/png") : null;
        }

        public string YTlink(string link)
        {
            if (link == null)
                return null;
            try
            {
                int youtu = link.IndexOf("youtu.be");
                
                if (youtu != -1)
                {
                    link = link.Substring(link.IndexOf("be/") + 3, 11);
                }
                else
                {
                    link = link.Substring(link.IndexOf("?v=") + 3, 11);
                }

                return "https://www.youtube.com/embed/" + link;
            }
            catch
            {
                return null;
            }
        }

        // GET: Advertises
        public async Task<IActionResult> Index(DateTime rentFrom, DateTime rentTo, string area, string type, string rent, string category)
        {
            var Add = from a in _context.Advertise
                      select a;

            Add = Add.Where(a => a.ConfirmationStatus == Advertise.StatusConfirmed);

            if (rentFrom != DateTime.MinValue && rentTo != DateTime.MinValue)
            {
                Add = Add.Where(a => !RangesIntersects(a.RentRanges, rentFrom, rentTo));
            }

            if (!String.IsNullOrEmpty(area))
            {
                Add = Add.Where(a => a.Address.Contains(area));
            }
            if (!String.IsNullOrEmpty(type))
            {
                Add = Add.Where(t => t.FlatType.Contains(type));
            }
            if (!String.IsNullOrEmpty(category))
            {
                Add = Add.Where(c => c.Category.Contains(category));
            }

            if (!String.IsNullOrEmpty(rent))
            {
                int low = 1000 * Int32.Parse(rent.Substring(0, 2));
                int up = 1000 * Int32.Parse(rent.Substring(4, 2));
                Add = Add.Where(r => r.Rent >= low
                    && r.Rent <= up);
            }

            return View(await Add.ToListAsync());
        }

        public async Task<IActionResult> MyRequests()
        {
            int currentUserID = Int32.Parse(HttpContext.Session.GetString("sId"));
            if (currentUserID == 0)
            {
                return RedirectToAction("Login", "Users");
            }

            var resp = from a in _context.AdvertiseRequest select a;

            Dictionary<string, Dictionary<string, List<AdvertiseRequest>>> result = new Dictionary<string, Dictionary<string, List<AdvertiseRequest>>>();

            resp = resp.Where(e => e.From == currentUserID || e.To == currentUserID);
            foreach (var x in resp)
            {
                var responseAdv = from b in _context.Advertise select b;
                responseAdv = responseAdv.Where(e => e.ID == x.AdvID);

                var tmp = await responseAdv.ToListAsync();
                x.Adv = tmp[0];

                string key;
                if (currentUserID == x.From)
                {
                    key = AdvertiseRequest.RequestOrderFrom;
                }
                else
                {
                    key = AdvertiseRequest.RequestOrderTo;
                }

                if (!result.ContainsKey(x.Type))
                    result[x.Type] = new Dictionary<string, List<AdvertiseRequest>>();

                if (!result[x.Type].ContainsKey(key))
                    result[x.Type][key] = new List<AdvertiseRequest>();
                
                result[x.Type][key].Add(x);
            }

            ViewBag.StatusArray = new List<string>() { Advertise.StatusConfirmed, Advertise.StatusDeclined, Advertise.StatusPending };

            return View(result);
        }

        public async Task<IActionResult> MyPosts()
        {
            string usermail = HttpContext.Session.GetString("sEmail");
            if (String.IsNullOrEmpty(usermail))
            {
                return RedirectToAction("Login", "Users");
            }
            var mypost = from mp in _context.Advertise
                         where mp.UserMail == usermail
                         select mp;
            return View(await mypost.ToListAsync());
        }

        // GET: Advertises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string tempUser = HttpContext.Session.GetString("sEmail");
            if (String.IsNullOrEmpty(tempUser))
            {
                return RedirectToAction("Login", "Users");
            }
            else
            {
                var userexist = await _context.User.SingleOrDefaultAsync(u => u.Email == tempUser);
                if (userexist == null)
                {
                    return RedirectToAction("Logout", "Users");
                }
            }

            if (id == null)
            {
                return NotFound();
            }

            var advertise = await _context.Advertise
                .SingleOrDefaultAsync(m => m.ID == id);
            if (advertise == null)
            {
                return NotFound();
            }

            advertise.YoutubeLink = YTlink(advertise.YoutubeLink);

            var images = from i in _context.Image
                         where i.AdvertiseID == id
                         select i;
            advertise.Images = await images.ToListAsync();

            var comments = from c in _context.Comment
                           where c.AdvertiseID == id
                           select c;
            advertise.Comments = await comments.ToListAsync();

            var reviews = from r in _context.Review
                          where r.AdvertiseID == id
                          select r;
            advertise.Reviews = await reviews.ToListAsync();

            var compliments = from c in _context.Compliment
                              where c.AdvertiseID == id
                              select c;

            advertise.Compliments = await compliments.ToListAsync();

            return View(advertise);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DoReview(Review review)
        {
            string usr = HttpContext.Session.GetString("sEmail");
            if (String.IsNullOrEmpty(usr))
            {
                return RedirectToAction("Login", "Users");
            }
            review.Reviewer = usr;

            var Reviewed = await _context.Review.SingleOrDefaultAsync(r => r.Reviewer == usr && r.AdvertiseID == review.AdvertiseID);

            if (Reviewed == null)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
            }
            else
            {
                Reviewed.ReviewStar = review.ReviewStar;
                _context.Update(Reviewed);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction("Details", new { id = review.AdvertiseID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DoCompliment(Compliment compliment)
        {
            string usr = HttpContext.Session.GetString("sEmail");
            if (String.IsNullOrEmpty(usr))
            {
                return RedirectToAction("Login", "Users");
            }
            compliment.Reviewer = usr;

            var Complimented = await _context.Compliment.SingleOrDefaultAsync(c => c.Reviewer == usr && c.AdvertiseID == compliment.AdvertiseID);

            if (Complimented == null)
            {
                _context.Add(compliment);
                await _context.SaveChangesAsync();
            }
            else
            {
                Complimented.Cleanness = compliment.Cleanness;
                Complimented.Comfort = compliment.Comfort;
                Complimented.PriceQuality = compliment.PriceQuality;
                Complimented.Staff = compliment.Staff;
                _context.Update(Complimented);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Details", new { id = compliment.AdvertiseID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DoComment([Bind(CmntString)] Comment comment)
        {
            string usr = HttpContext.Session.GetString("sEmail");
            if (String.IsNullOrEmpty(usr))
            {
                return RedirectToAction("Login", "Users");
            }
            comment.CommentTime = DateTime.Now;
            comment.Commenter = usr;
            _context.Add(comment);
            await _context.SaveChangesAsync();

HouseRent/Views/Advertises/Create.cshtml
@model HouseRent.Models.Advertise

@{
    ViewData["Title"] = "Post an Advertise";
}

<h3>Create an advertisement for your house</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Heading" class="control-label"></label>
                <input asp-for="Heading" class="form-control" />
                <span asp-validation-for="Heading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YoutubeLink" class="control-label"></label>
                <input asp-for="YoutubeLink" class="form-control" />
                <span asp-validation-for="YoutubeLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlatSize" class="control-label"></label>
                <input asp-for="FlatSize" class="form-control" />
                <span asp-validation-for="FlatSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlatType" class="control-label"></label>
                <select name="FlatType" class="form-control">
                    <option value="Apartment">Apartment</option>
                    <option value="Hostel">Hostel</option>
                    <option value="Hotel">Hotel</option>
                    <option value="Room">Room</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select name="Category" class="form-control">
                    <option value="1">1</option>
                    <option value="2-3" selected>2-3</option>
                    <option value="4-5">4-5</option>
                    <option value="6+">6+</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Rent" class="control-label"></label>
                <input asp-for="Rent" class="form-control" />
                <span asp-validation-for="Rent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlatDetails" class="control-label"></label>
                <input asp-for="FlatDetails" class="form-control" />
                <span asp-validation-for="FlatDetails" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UtilitiesBill" class="control-label"></label>
                <input asp-for="UtilitiesBill" class="form-control" />
                <span asp-validation-for="UtilitiesBill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OtherBill" class="control-label"></label>
                <input asp-for="OtherBill" class="form-control" />
                <span asp-validation-for="OtherBill" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Images </label>
                <input type="file" name="imgs" id="imgs" accept=".jpg, .jpeg, .png" multiple required/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HouseRent/Views/Advertises/Details.cshtml
@model HouseRent.Models.Advertise
@using Microsoft.AspNetCore.Http
@using System;


@{
    ViewData["Title"] = @Html.DisplayFor(model => model.Heading);

}

<h2>@Html.DisplayFor(model => model.Heading) </h2>
<br />

@*Google map starts....*@
<body>
    <style>
        #map {
            height: 400px;
            width: 400px;
        }
    </style>
    <h3> See in Google map </h3>
    <div id="map"></div>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        function area() {
            var location = "@Model.Address";
            return location;
        }
    </script>

    <script src="~/googlemap/googlemap.js"></script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAcNrI8A1S4IInSiDqN730I5moq-Hv-k88&callback=initMap">
    </script>
</body>
@*Google map Done!!!!*@

<br /><br />
<h3>Review</h3>
<hr />
<div>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .checked {
            color: orange;
        }
    </style>
    @{
        int Five = 0, Four = 0, Three = 0, Two = 0, One = 0;
        int YourRate = 0;
        string user = @Context.Session.GetString("sEmail");
    }
    @foreach (var review in Model.Reviews)
    {
        //assigning your rating
        if (review.Reviewer == user)
        {
            YourRate = review.ReviewStar;
        }

        if (review.ReviewStar == 5)
        {
            Five++;
        }
        else if (review.ReviewStar == 4)
        {
            Four++;
        }
        else if (review.ReviewStar == 3)
        {
            Three++;
        }
        else if (review.ReviewStar == 2)
        {
            Two++;
        }
        else if (review.ReviewStar == 1)
        {
            One++;
        }
    }
    @{
        double totalRatings = Five + Four + Three + Two + One;
        double totalStars = Five * 5 + Four * 4 + Three * 3 + Two * 2 + One * 1;
        double avgRating = totalStars / totalRatings;

        for (int i = 1; i <= 5; i++)
        {
            if (i <= Math.Round(avgRating))
            {
                <span class="fa fa-star checked"></span>
            }
            else
            {
                <span class="fa fa-star"></span>
            }

        }

        int Cleanness = 0, Comfort = 0, PriceQuality = 0, Staff = 0;
        bool VotedCleanness = false, VotedComfort = false, VotedQuality = false, VotedStaff = false, Voted = false;
        @foreach (var compliment in Model.Compliments)
        {
            if(compliment.Reviewer == user)
            {
                Voted = true;
                if(compliment.Cleanness == 1)
                {
                    VotedCleanness = true;
                }
                if(compliment.Comfort == 1)
                {
                    VotedComfort = true;
                }
                if(compliment.PriceQuality == 1)
                {
                    VotedQuality = true;
                }
                if(compliment.Staff == 1)
                {
                    VotedStaff = true;
                }
            }
            if (compliment.Cleanness == 1)
            {
                Cleanness++;
            }
            if (compliment.Comfort == 1)
            {
                Comfort++;
            }
            if (compliment.PriceQuality == 1)
            {
                PriceQuality++;
            }
            if (compliment.Staff == 1)
            {
                Staff++;
            }
        }
    }
    }

    <p> <b>Rating:</b> @System.Math.Round(avgRating, 2) Out of 5 (<b>Total Review:</b> @totalRatings)</p>
    <p><b>5-Stars: </b> @Five &nbsp; <b>4-Stars:</b> @Four &nbsp; <b>3-Stars:</b>
    @Three &nbsp; <b>2-Stars:</b> @Two &nbsp; <b>1-Stars:</b> @One</p>
</div>

@*Do review*@
<div class="container">
    @if (YourRate > 0)
    {
        <h4> You Rated @YourRate Out of 5.</h4>
    }
    else
    {
        <h4>You didn't rate it. You can always change your Ratings.</h4>
    }

    <form asp-action="DoReview">
        <input type="hidden" name="AdvertiseID" value="@Model.ID" />

        <label class="radio-inline">
            <input type="radio" name="ReviewStar" value="5" required>5-Star
        </label>
        <label class="radio-inline">
            <input type="radio" name="ReviewStar" value="4">4-Star
        </label>
        <label class="radio-inline">
            <input type="radio" name="ReviewStar" value="3">3-Star
        </label>
        <label class="radio-inline">
            <input type="radio" name="ReviewStar" value="2">2-Star
        </label>
        <label class="radio-inline">
            <input type="radio" name="ReviewStar" value="1">1-Star
        </label>

        <input type="submit" value="Rate This" class="btn btn-default btn-sm" />
    </form>
</div>

<div>
    <h3>Compliments</h3>
    <hr />

    <form asp-action="DoCompliment">
        <input type="hidden" name="AdvertiseID" value="@Model.ID" />
        <div style="float: left; margin-right: 20px;">
            <img src="https://firstclasscleaningfla.com/content/wp-content/uploads/2016/05/shutterstock_155294633.jpg"
                 alt="cleanness"
                 width="150"
                 height="150" />
            @if (VotedCleanness)
            {
                <p><input type="radio" name="Cleanness" value="1" checked>Cleanness</p>
            }
            else
            {
                <p><input type="radio" name="Cleanness" value="1">Cleanness</p>
            }
            <p>Total votes: @Cleanness</p>
        </div>
        <div style="float: left; margin-right: 20px;">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSBtJp-zxwml7d5hYmoueckbXqc06MDKa9Mb_C2L6WAUS5yrWMRhAS8qvKWjkCgsHEf-RWUd-79o73j0sr6HRY_Sv7blm6yHUYbQ&usqp=CAU&ec=45732303"
                 alt="comfort"
                 width="150"
                 height="150" />
            @if (VotedComfort)
            {
                <p><input type="radio" name="Comfort" value="1" checked>Comfort</p>
            }
            else
            {
                <p><input type="radio" name="Comfort" value="1">Comfort</p>
            }
            <p>Total votes: @Comfort</p>
        </div>
        <div style="float: left; margin-right: 20px;">
            <img src="https://st.depositphotos.com/1007566/1473/v/950/depositphotos_14734381-stock-illustration-best-choice.jpg"
                 alt="price/quality"
                 width="150"
                 height="150" />
            @if (VotedQuality)
            {
                <p><input type="radio" name="PriceQuality" value="1" checked>Price / Quality</p>
            }
            else
            {
                <p><input type="radio" name="PriceQuality" value="1">Price / Quality</p>
            }
            <p>Total votes: @PriceQuality</p>
        </div>
        <div>
            <img src="https://cache3.youla.io/files/images/720_720_out/5d/1f/5d1f395965bcf144044af8cd.jpg"
                 alt="staff"
                 width="150"
                 height="150" />
            @if (VotedStaff)
            {
                <p><input type="radio" name="Staff" value="1" checked>Staff</p>
            }
            else
            {
                <p><input type="radio" name="Staff" value="1">Staff</p>
            }
            <p>Total votes: @Staff</p>
        </div>
        @if (Voted)
        {
            <input type="submit" value="Recompliment This" class="btn btn-default btn-sm" />
        }
        else
        {
            <input type="submit" value="Compliment This" class="btn btn-default btn-sm" />
        }
    </form>
</div>

<div style="margin-top: 20px;">
    <h3>Details Informations</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserMail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserMail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostTime)
        </dd>
        @*<dt>
                @Html.DisplayNameFor(model => model.RentDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.RentDate)
            </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FlatSize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlatSize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FlatDetails)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlatDetails)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UtilitiesBill)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UtilitiesBill)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OtherBill)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OtherBill)
        </dd>
    </dl>
</div>

<h3>House Images</h3>
<hr />
<table>
    <tr>
        @foreach (var img in Model.Images)
        {
            <td><img src="@Url.Action("GetImg", "Advertises", new { id = img.ID })" class="img-responsive" height="200" width="200" /></td>
        }

    </tr>
</table>

<br /><br />
<h3>See in Youtube</h3>
<hr />
@{ 
    if(String.IsNullOrEmpty(Model.YoutubeLink))
    {
<p style="color:darkred;">No Valid Youtube URL Given </p> }
else
{
<iframe width="854" height="480" src=@Model.YoutubeLink frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> } }

<br />
<br />
<h3>Rent</h3>

<body>

    <link href='~/fullcalendar/main.css' rel='stylesheet' />
    <script src='~/fullcalendar/main.js'></script>

    <div id='calendar'></div>
    <form asp-action="Rent">
        <div>
            <input type="hidden" name="id" value="@Model.ID" />
        </div>
        <div>
            <label class="control-label">Rent From</label>
            <input type="date" name="rentFrom" class="form-control" />
        </div>
        <div class="form-group">
            <label class="control-label">Rent To</label>
            <input type="date" name="rentTo" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Rent" class="btn btn-success" />
        </div>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $.ajax({
                type: 'GET',
                contentType: 'charset=UTF-8',
                data: {id: @Model.ID},
                url: "/Advertises/GetRentInfo",
                cache: false,
                success: function (data) {
                    console.log(data);
                    var calendarEl = document.getElementById('calendar');
                    var calendar = new FullCalendar.Calendar(calendarEl, {
                        initialView: 'dayGridMonth',
                        headerToolbar: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'dayGridMonth'
                        },
                        events: JSON.parse(data)
                    });
                    calendar.render();
                }
            });
        });

    </script>
</body>

<br /><br />
@*comment box*@
<div class="row">
    <div class="col-md-4">
        <form asp-action="DoComment">
            <div>
                <input type="hidden" name="AdvertiseID" value="@Model.ID" />
            </div>
            <div class="form-group">
                <label class="control-label">Write a Comment</label>
                <textarea name="CommentText" class="form-control" rows="4" cols="50" required></textarea>
            </div>
            <div class="form-group">
                <div>
                    <input type="checkbox" name="Anonymous" value="True"> Anonymous Comment
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
@*Comment box end*@
<div>
    @foreach (var cmnt in Model.Comments)
    {
        <table class="table-responsive">
            <tr>
                @if (cmnt.Anonymous)
                {
                    <th>Anonymous  &nbsp; &nbsp; </th>
                }
                else
                {
                    <th>@cmnt.Commenter &nbsp; &nbsp; </th>
                }
                <td>@cmnt.CommentTime &nbsp; &nbsp; </td>
                @if (user == cmnt.Commenter)
                {
                    <td>  <a asp-action="DeleteComment" asp-route-id="@cmnt.ID" class="btn btn-warning btn-xs">Delete</a></td>
                }

            </tr>
            <tr>
                <td colspan="3"> @cmnt.CommentText</td>
            </tr>
        </table>
        <br />
    }
</div>
<br />

HouseRent/Views/Advertises/Index.cshtml
@model IEnumerable<HouseRent.Models.Advertise>
@using System
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = "Find your dream home";
}

<h2>Find Your Dream Home...</h2>
<br />
<form asp-action="Index" asp-controller="Advertises" method="get">

    <table class="table-responsive">
        <tr>
            <td>
                <input type="date" name="rentFrom" class="form-control" />
            </td>
            <td>
                <input type="date" name="rentTo" class="form-control" />
            </td>
            <td>
                <input type="text" placeholder="Area" name="area" class="form-control" />
            </td>
            <td>
                <select name="type" class="form-control">
                    <option value="">House Type</option>
                    <option value="Apartment">Apartment</option>
                    <option value="Hostel">Hostel</option>
                    <option value="Hotel">Hotel</option>
                    <option value="Room">Room</option>
                </select>
            </td>
            <td>
                <select name="rent" class="form-control">
                    <option value="">Rent Range</option>
                    <option value="0-50$">0-50$</option>
                    <option value="51-100$">51-100$</option>
                    <option value="101-200$">101-200$</option>
                    <option value="201-400$">201-400$</option>
                </select>
            </td>
            <td>
                <select name="category" class="form-control">
                    <option value="">Amount of people</option>
                    <option value="1">1</option>
                    <option value="2-3">2-3</option>
                    <option value="4-5">4-5</option>
                    <option value="6+">6+</option>
                </select>
            </td>
            <td>
                <input type="submit" value="Search" class="btn btn-info" />
            </td>
        </tr>
    </table>
</form>

<br /><br />

<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.RentDate)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlatType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlatDetails)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.RentDate)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlatType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlatDetails)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                    @if (@Context.Session.GetString("sRole") == "admin")
                    {
                        <a asp-action="Delete" asp-route-id="@item.ID"> Delete</a>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>